# Generated by Django 5.2.14 on 2026-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='gallery/covers/', verbose_name='تصویر کاور'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='slug',
            field=models.SlugField(blank=True, help_text='اگر خالی بماند، به صورت خودکار از عنوان ساخته می\u200cشود.', max_length=150, verbose_name='نام در آدرس'),
        ),
    ]
