# Generated by Django 5.2.14 on 2026-05-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerypage_cover_image_gallerypage_intro_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(blank=True, help_text='متن کوتاه زیر تصویر یا توضیح تکمیلی.', verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش زودتر در گالری.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery_page',
            field=models.ForeignKey(help_text='تصویر به کدام صفحه گالری تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerypage', verbose_name='صفحه گالری'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='فایل تصویر را بارگذاری کنید.', upload_to='gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فقط تصاویر فعال در سایت نمایش داده می\u200cشوند.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, help_text='در صورت نیاز برای این تصویر عنوان وارد کنید.', max_length=150, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='تصویر شاخص این صفحه گالری.', upload_to='gallery/covers/', verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح کوتاه مدیریتی یا توضیح عمومی صفحه گالری.', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش زودتر در لیست گالری\u200cها.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='متنی که بالای تصاویر این گالری در سایت نمایش داده می\u200cشود.', verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فقط گالری\u200cهای فعال در سایت قابل مشاهده هستند.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='برای ساخت زیرگالری، صفحه والد را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.gallerypage', verbose_name='گالری والد'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'invalid': 'نام در آدرس فقط می\u200cتواند شامل حروف، عدد، خط فاصله و زیرخط باشد.'}, help_text='اگر خالی بماند، به صورت خودکار از عنوان ساخته می\u200cشود.', max_length=150, verbose_name='نام در آدرس'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='title',
            field=models.CharField(help_text='نامی که در لیست گالری و صفحه نمایش داده می\u200cشود.', max_length=150, verbose_name='عنوان'),
        ),
    ]
