# Generated by Django 5.2.14 on 2026-06-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryimage_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان ویدیو.', max_length=150, verbose_name='عنوان')),
                ('platform', models.CharField(choices=[('youtube', 'یوتیوب'), ('aparat', 'آپارات')], help_text='ویدیو از کدام سرویس جاسازی می\u200cشود.', max_length=10, verbose_name='سرویس')),
                ('video_url', models.URLField(help_text='آدرس صفحه ویدیو در یوتیوب یا آپارات را وارد کنید (نه کد جاسازی).', verbose_name='آدرس ویدیو')),
                ('caption', models.TextField(blank=True, help_text='توضیح کوتاه زیر ویدیو.', verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=True, help_text='فقط ویدیوهای فعال در سایت نمایش داده می\u200cشوند.', verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش زودتر.', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('gallery_page', models.ForeignKey(help_text='ویدیو به کدام صفحه گالری تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.gallerypage', verbose_name='صفحه گالری')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
