# Generated by Django 5.2.14 on 2026-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'خانه'), ('about', 'درباره ما')], max_length=20, unique=True, verbose_name='کلید صفحه')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن صفحه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوای صفحه',
                'verbose_name_plural': 'محتواهای صفحه',
                'ordering': ['page_key'],
            },
        ),
    ]
