# Generated by Django 5.2.14 on 2026-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepagecontent',
            name='body',
            field=models.TextField(help_text='متن اصلی که در صفحه نمایش داده می\u200cشود.', verbose_name='متن صفحه'),
        ),
        migrations.AlterField(
            model_name='sitepagecontent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فقط محتوای فعال در صفحه عمومی استفاده می\u200cشود.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='sitepagecontent',
            name='page_key',
            field=models.CharField(choices=[('home', 'خانه'), ('about', 'درباره ما')], help_text='مشخص می\u200cکند این محتوا مربوط به کدام صفحه است.', max_length=20, unique=True, verbose_name='کلید صفحه'),
        ),
        migrations.AlterField(
            model_name='sitepagecontent',
            name='title',
            field=models.CharField(help_text='عنوان اصلی صفحه.', max_length=150, verbose_name='عنوان'),
        ),
    ]
