# Generated by Django 5.2.14 on 2026-05-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_sitepagecontent_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepagecontent',
            name='page_key',
            field=models.CharField(choices=[('home', 'خانه'), ('about', 'درباره ما'), ('schedule', 'برنامه کلاس\u200cها')], help_text='مشخص می\u200cکند این محتوا مربوط به کدام صفحه است.', max_length=20, unique=True, verbose_name='کلید صفحه'),
        ),
    ]
