# Generated by Django 5.2.14 on 2026-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_sitepagecontent_page_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='تصویر بزرگ بالای صفحه. در حال حاضر فقط برای صفحه خانه استفاده می\u200cشود.', upload_to='pages/', verbose_name='تصویر اصلی صفحه'),
        ),
        migrations.AddField(
            model_name='sitepagecontent',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای موتورهای جستجو و اشتراک\u200cگذاری (حداکثر ۱۶۰ کاراکتر).', max_length=160, verbose_name='توضیحات متا (سئو)'),
        ),
    ]
