# Generated by Django 5.2.14 on 2026-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیام\u200cهای تماس'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='موضوع'),
        ),
    ]
