# Generated by Django 5.2.14 on 2026-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'ایمیل وارد شده معتبر نیست.'}, help_text='آدرس ایمیلی که پاسخ به آن ارسال می\u200cشود.', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(help_text='نام فرستنده پیام.', max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='برای پیگیری، وضعیت خوانده شدن پیام را مشخص کنید.', verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='متن کامل پیام ارسالی.', verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='در صورت نیاز شماره تماس را وارد کنید.', max_length=30, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='موضوع اصلی پیام.', max_length=150, verbose_name='موضوع'),
        ),
    ]
