# Generated by Django 4.2.30 on 2026-05-15 14:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
