# Generated by Django 5.2.14 on 2026-05-17 17:52

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_persian_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(error_messages={'unique': 'این ساز قبلا ثبت شده است.'}, help_text='نام هر ساز را فقط یک بار ثبت کنید.', max_length=100, unique=True, verbose_name='نام ساز'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='biography',
            field=models.TextField(help_text='توضیح کوتاه یا کامل درباره سابقه و فعالیت\u200cهای استاد.', verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_city',
            field=models.CharField(help_text='شهر محل تولد استاد.', max_length=100, verbose_name='شهر محل تولد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_province',
            field=models.CharField(help_text='استان محل تولد استاد.', max_length=100, verbose_name='استان محل تولد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(help_text='تاریخ تولد را به صورت شمسی وارد کنید.', verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش زودتر در لیست اساتید.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.CharField(help_text='مدرک یا سابقه آموزشی استاد.', max_length=255, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(help_text='نام استاد را وارد کنید.', max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='instruments',
            field=models.ManyToManyField(help_text='یک یا چند ساز که این استاد تدریس می\u200cکند را انتخاب کنید.', related_name='teachers', to='teachers.instrument', verbose_name='سازها'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فقط اساتید فعال در سایت نمایش داده می\u200cشوند.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(help_text='نام خانوادگی استاد را وارد کنید.', max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(help_text='تصویر پرتره استاد را بارگذاری کنید.', upload_to='teachers/', verbose_name='تصویر پروفایل'),
        ),
    ]
