# Generated by Django 5.2.14 on 2026-05-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_instrument_name_alter_teacher_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birth_city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birth_province',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='education',
        ),
    ]
