"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file (gitignored) into os.environ if present.
# On Runflare, real environment variables are used instead and take precedence.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w(p+t0x6&*4295%5nedht10@0yz)bbdth9&0jw8xe$tnk(sgyq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['aramesh-academy.runflare.run', 'api.runflare.com', 'localhost', '127.0.0.1','aramesh-academy.ir']

CSRF_TRUSTED_ORIGINS = [
    'https://aramesh-academy.ir',
    'https://aramesh-academy.runflare.run',
]

# Runflare terminates TLS at its proxy and forwards the original scheme in this header.
# Without it, Django thinks every request is http and builds http:// URLs (breaks OG/canonical).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_jalali',
    'core',
    'pages',
    'teachers',
    'schedules',
    'contact',
    'gallery',
    'testimonials',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gallery.context_processors.gallery_nav_tree',
                'core.context_processors.site_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'database/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/public/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "public", "static")

# Using a separate directory for STATICFILES_DIRS to avoid E002 conflict
# If development needs access to static files, ensure they exist here.
STATICFILES_DIRS = [
    BASE_DIR / 'static_dev', 
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/public/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "public", "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site Information
SITE_EMAIL = 'aramesh.music.acad@gmail.com'
SITE_PHONES = ['+98 21 4445 7748', '+98 990 233 8431', '+98 21 4445 7746', '+98 21 4613 3707']
SITE_ADDRESS = 'تهران، اشرفی اصفهانی، پایین تر از تیراژه، نبش خ امام حسین، پلاک ۱۴۲ طبقه دوم '

# Social media (leave empty to hide the link). Override via env vars if needed.
SITE_INSTAGRAM = os.environ.get('SITE_INSTAGRAM', 'https://www.instagram.com/arameshmusic.academy/')
SITE_TELEGRAM = os.environ.get('SITE_TELEGRAM', 'https://t.me/arameshmusicacademyconcert')

# Working hours shown on the contact page — one entry per displayed line.
SITE_HOURS = [
    'شنبه تا چهارشنبه: ۱۰ تا ۲۱ (به غیر از ایام تعطیل)',
    'پنج‌شنبه: ۱۰ تا ۱۴',
]

# Email
# Defaults to the console backend so local dev and tests never need real SMTP credentials.
# In production, set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend and the
# EMAIL_HOST / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD env vars on Runflare.
def _env_int(name, default):
    """Read an int env var, falling back to default if it's missing or malformed.
    A bad email value must never crash app startup."""
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return int(default)


EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = _env_int('EMAIL_PORT', 587)
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', SITE_EMAIL)

# Where new contact-form submissions are emailed.
CONTACT_NOTIFICATION_EMAIL = os.environ.get('CONTACT_NOTIFICATION_EMAIL', SITE_EMAIL)

# Slug of the GalleryPage whose images are shown on the About page (academy's physical space).
ABOUT_GALLERY_SLUG = os.environ.get('ABOUT_GALLERY_SLUG', 'academy-space')

# Google Analytics 4 measurement ID (e.g. G-XXXXXXXXXX). Empty = analytics disabled.
GOOGLE_ANALYTICS_ID = os.environ.get('GOOGLE_ANALYTICS_ID', '')

# ── Django admin theme (django-jazzmin) ──────────────────────────────────────
JAZZMIN_SETTINGS = {
    'site_title': 'مدیریت آموزشگاه آرامش',
    'site_header': 'آموزشگاه موسیقی آرامش',
    'site_brand': 'آموزشگاه آرامش',
    'welcome_sign': 'به پنل مدیریت آموزشگاه موسیقی آرامش خوش آمدید',
    'copyright': 'آموزشگاه موسیقی آرامش',
    'search_model': ['teachers.Teacher', 'contact.ContactMessage'],

    # Top menu: quick link to view the live site
    'topmenu_links': [
        {'name': 'مشاهده سایت', 'url': '/', 'new_window': True},
    ],

    # Order of app sections in the sidebar
    'order_with_respect_to': [
        'teachers', 'schedules', 'gallery', 'pages', 'testimonials', 'contact', 'auth',
    ],

    # FontAwesome icons per model
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'teachers': 'fas fa-chalkboard-teacher',
        'teachers.Teacher': 'fas fa-chalkboard-teacher',
        'teachers.Instrument': 'fas fa-guitar',
        'schedules': 'fas fa-calendar-alt',
        'schedules.ClassSession': 'fas fa-calendar-alt',
        'gallery': 'fas fa-images',
        'gallery.GalleryPage': 'fas fa-folder-open',
        'gallery.GalleryImage': 'fas fa-image',
        'gallery.Video': 'fas fa-video',
        'pages': 'fas fa-file-alt',
        'pages.SitePageContent': 'fas fa-file-alt',
        'testimonials': 'fas fa-comment-dots',
        'testimonials.Testimonial': 'fas fa-comment-dots',
        'contact': 'fas fa-envelope',
        'contact.ContactMessage': 'fas fa-envelope-open-text',
    },
    'default_icon_parents': 'fas fa-chevron-circle-left',
    'default_icon_children': 'fas fa-circle',

    # Keep the familiar stacked fieldsets instead of tabbed forms
    'changeform_format': 'single',
    'show_ui_builder': False,
    'related_modal_active': True,
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'default_theme_mode': 'light',
    'sidebar_nav_flat_style': True,
    'navbar_fixed': True,
    'sidebar_fixed': True,
}
