# Generated by Django 5.2.14 on 2026-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='نام والد یا هنرجویی که این نظر را گفته است.', max_length=120, verbose_name='نام')),
                ('relation', models.CharField(blank=True, help_text='برای مثال: والد هنرجوی پیانو (اختیاری).', max_length=120, verbose_name='نسبت')),
                ('quote', models.TextField(help_text='متن کوتاه نظر یا تجربه.', verbose_name='متن نظر')),
                ('is_active', models.BooleanField(default=True, help_text='فقط نظرهای فعال در سایت نمایش داده می\u200cشوند.', verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش زودتر.', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
