# Generated by Django 5.2.14 on 2026-05-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_admin_labels_course_timestamps_weekday_order'),
        ('teachers', '0004_alter_instrument_name_alter_teacher_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت مشخص بودن، ظرفیت این جلسه را وارد کنید.', null=True, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(help_text='کلاسی که این جلسه به آن تعلق دارد.', on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='schedules.course', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(help_text='ساعت پایان جلسه.', verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فقط جلسه\u200cهای فعال در برنامه سایت نمایش داده می\u200cشوند.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='notes',
            field=models.TextField(blank=True, help_text='در صورت نیاز توضیح کوتاه درباره این جلسه بنویسید.', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(help_text='ساعت آغاز جلسه.', verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='teacher',
            field=models.ForeignKey(help_text='استادی که این جلسه را برگزار می\u200cکند.', on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='teachers.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='weekday',
            field=models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یکشنبه'), ('mon', 'دوشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنجشنبه'), ('fri', 'جمعه')], help_text='روز برگزاری این جلسه را انتخاب کنید.', max_length=3, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(error_messages={'unique': 'کلاسی با این نام قبلا ثبت شده است.'}, help_text='برای هر کلاس یک نام یکتا وارد کنید.', max_length=120, unique=True, verbose_name='نام کلاس'),
        ),
    ]
