# Generated by Django 5.2.14 on 2026-05-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_classsession_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='capacity',
        ),
    ]
