# Generated by Django 5.2.14 on 2026-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_classsession_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس\u200cها'},
        ),
        migrations.AddField(
            model_name='course',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کمتر یعنی نمایش بالاتر در جدول برنامه\u200cها.', verbose_name='ترتیب نمایش'),
        ),
    ]
