# Generated by Django 5.2.14 on 2026-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_course_options_course_display_order'),
        ('teachers', '0005_remove_teacher_birth_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='course',
        ),
        migrations.AddField(
            model_name='classsession',
            name='instruments',
            field=models.ManyToManyField(help_text='یک یا چند سازی که استاد در این جلسه تدریس می\u200cکند را انتخاب کنید.', related_name='class_sessions', to='teachers.instrument', verbose_name='سازها'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
